# Proyecto para entrega Tipos Abstractos de Datos 2022
#
# ( Añadir las reglas necesarias para la correcta compilación de todas las implementaciones que se piden)


pruebaColas: pruebaColas.c cola.h cola.o pruebaColas.o
	gcc -g pruebaColas.c cola.o -o pruebaColas

cola.o: cola.c cola.h 
	gcc -g -c cola.c -o cola.o