# Proyecto para entrega Tipos Abstractos de Datos 2022
#
# ( Añadir las reglas necesarias para la correcta compilación de todas las implementaciones que se piden)


pruebaPilas: pruebaPilas.c pila.h pila.o pruebaPilas.o
	gcc -g pruebaPilas.c pila.o -o pruebaPilas

pila.o: pila.c pila.h 
	gcc -g -c pila.c -o pila.o